### ISSUE TITLE
Does not work with 2023.2 

### ISSUE THREAD

**Issue by dt1729** [Xilinx/kria-base-hardware#2]
Hi team, I am trying to compile the xsa file for kria som kv260 vision starter kit using vivado 2023.2 however I'm getting an error about get_property from the xsa compiler:

```
INFO: [Common 17-14] Message 'Board 49-26' appears 100 times and further instances of the messages will be disabled. Use the Tcl command set_msg_config to change the current settings.
WARNING: [Vivado 12-4842] No board parts matched 'get_board_parts {}'.
ERROR: [Common 17-55] 'get_property' expects at least one object.
Resolution: If [get_<value>] was used to populate the object, check to make sure this command returns at least one valid object.
INFO: [Common 17-206] Exiting Vivado at Sun Jul 28 01:59:28 2024...
make: *** [Makefile:29: project/*.xsa] Error 1
```

**Comment by Zzs1eep** [comment]
Some makefiles which generated by 2023.2 are WRONG.If you use an IP core which was created by yourself,you can try to change the Makefile in IP package

**Comment by chris-xlnx** [comment]
It looks like it isn’t finding the board files for kv260_som.  I believe this will happen if you didn’t install the SOM devices when you installed Vivado.  There isn’t a lot of information in the report, but I see that there are > 100 instances of the message 'Board 49-26' which happens to be ‘Cannot add board part <board>’.

**Comment by dt1729** [comment]
Hi I fixed it about a month ago by downloading .xsa files from the link given in the older documentation.

**Comment by chkohn** [comment]
Issue seems to be obsolete
